[package]
name = "wasi-rng"
version = "0.1.0"
authors = ["Julian Popescu <jpopesculian@gmail.com>"]
edition = "2018"
license = "MIT"
description = "An random number generator implementation for WASI"

[dependencies]
wasi = "0.9"
rand_core = "0.5"
